field: 9a8c6fad-fe27-4467-a444-76f5dbea6adb # Text and Image
fieldLayouts:
  a2278eff-d8dc-4ab9-a6a1-e1d98d2a67f5:
    tabs:
      -
        elements:
          -
            fieldUid: 09ee1e9f-f518-4b68-bb88-8e0c549a98da # Rich text field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  09ee1e9f-f518-4b68-bb88-8e0c549a98da: # Rich text field
    contentColumnType: text
    fieldGroup: null
    handle: richTextField
    instructions: 'Velg denne for formaterbar tekst'
    name: 'Rich text field'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: richText
name: 'Rich Text'
sortOrder: 3
