fieldLayouts:
  0f5e76a5-60ee-4e3b-ad84-f1d19baa2d95:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: omVillVillVest
hasTitleField: false
name: 'Om Vill Vill Vest'
section: 9e64103f-dc8f-4c68-83be-0dc3d1649662 # Om Vill Vill Vest
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
