contentColumnType: text
fieldGroup: db276e6f-7ce0-4275-85c3-dc7126081f28 # Meta fields
handle: seoDescription
instructions: ''
name: seoDescription
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
