fieldLayouts:
  ec47ab8a-127a-4788-956e-9efec7149dfc:
    tabs:
      -
        elements:
          -
            fieldUid: 5f001340-1034-4a54-bafc-e4e78c6a5d76 # One image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: favicon
name: Favicon
