fieldLayouts:
  fceb3649-ebb9-41bb-a26a-1889b218fb71:
    tabs:
      -
        elements:
          -
            fieldUid: aa6f0f92-8c74-4418-91bc-98782f0d712a # Logo Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3a1eb6ad-0e12-458a-a40f-4142aef3deb7 # Logo Image Dark
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b42fb653-efdf-4f39-924e-c581b483b853 # Logo Mobile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9d2bdeb4-501c-458b-92bc-44194ba2e2f6 # Logo Mobile Dark
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: header
name: Header
