fieldLayouts:
  6934fdb7-e846-427d-a016-6c8301100533:
    tabs:
      -
        elements:
          -
            fieldUid: 9a8c6fad-fe27-4467-a444-76f5dbea6adb # Text and Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: konferanseprogram
name: Konferanseprogram
