fieldLayouts:
  88ef11c8-c423-4799-b8a8-a4ab08a43d6e:
    tabs:
      -
        elements:
          -
            fieldUid: 9a8c6fad-fe27-4467-a444-76f5dbea6adb # Text and Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: konferanseTekst
name: Konferanse
