fieldLayouts:
  47d2a2ae-ed7c-4877-97cf-9825b9e8695e:
    tabs:
      -
        elements:
          -
            fieldUid: 5f001340-1034-4a54-bafc-e4e78c6a5d76 # One image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: kontakt
name: Kontakt
