fieldLayouts:
  edd63cc4-8697-4731-b8bf-865c0e5b7a87:
    tabs:
      -
        elements:
          -
            fieldUid: 248f81f8-47af-4b2a-8e1e-d2c418c20960 # Partnere Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b0cbef75-0120-4015-8606-d249df047d82 # Partnere Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Partnere
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ab0087ee-3de1-4d43-80e3-6417c0451045 # Hovedpartnere
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aa79297f-c886-4a09-be2e-4e56e2d618f3 # Faglige Partnere
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 01ae3db8-4df7-4371-a601-0f9c4bd8ee67 # Kuratorer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4bdf0e3e-53f7-4227-b46e-d8ad522edaf6 # Sponsorer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'All Partners'
        sortOrder: 2
handle: partnere
name: Partnere
