fieldLayouts:
  2f2330f2-a226-432c-ae8d-8ab365c94b74:
    tabs:
      -
        elements:
          -
            fieldUid: 9a8c6fad-fe27-4467-a444-76f5dbea6adb # Text and Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: praktiskInfo
name: 'Praktisk info'
