fieldLayouts:
  1cd38f77-6175-45b9-ac36-04de53289518:
    tabs:
      -
        elements:
          -
            fieldUid: fef089a6-adb4-4e72-9b9e-419922a070ad # Ticket Image 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9b3a5a88-b93f-4584-9f88-df5455c755a8 # Ticket Image 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 02545eca-eed3-449f-8bd1-2bcb3ef87a8e # Ticket Image 3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: tickets
name: Tickets
