enableVersioning: true
handle: artistaktiviteter
name: Artistaktiviteter
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ff6d129f-58c1-49a3-82d4-b5e2571a753e: # villvillvest
    enabledByDefault: true
    hasUrls: true
    template: _singles/artistaktiviteter
    uriFormat: artistaktiviteter
type: single
