enableVersioning: true
handle: konferanser
name: Konferanser
propagationMethod: all
siteSettings:
  ff6d129f-58c1-49a3-82d4-b5e2571a753e: # villvillvest
    enabledByDefault: true
    hasUrls: true
    template: konferanser/_entry
    uriFormat: 'konferanser/{slug}'
type: channel
