enableVersioning: true
handle: nyheter
name: Nyheter
propagationMethod: all
siteSettings:
  ff6d129f-58c1-49a3-82d4-b5e2571a753e: # villvillvest
    enabledByDefault: true
    hasUrls: true
    template: nyheter/_entry
    uriFormat: 'nyheter/{slug}'
type: channel
