enableVersioning: true
handle: omVillVillVest
name: 'Om Vill Vill Vest'
propagationMethod: all
siteSettings:
  ff6d129f-58c1-49a3-82d4-b5e2571a753e: # villvillvest
    enabledByDefault: true
    hasUrls: true
    template: _singles/om-vill-vill-vest
    uriFormat: om-vill-vill-vest
type: single
